export enum FishCategory {
  SALTWATER = "saltwater",
  IMPORTED = "imported",
}

export interface Fish {
  id: string
  nameEn: string
  nameFil: string
  description: string
  price: number
  oldPrice?: number
  image: string
  category: FishCategory
  origin: string
  isHighSupply: boolean
  isOnSale: boolean
  isFrozen: boolean
  supplyLevel: number // 1-10 scale
  weight: {
    min: number
    max: number
  }
}

export const allFish: Fish[] = [
  {
    id: "galunggong",
    nameEn: "Mackerel Scad",
    nameFil: "Galunggong",
    description: "A staple in Filipino cuisine, known as the 'poor man's fish' but rich in flavor and nutrients.",
    price: 120,
    oldPrice: 150,
    image: "/images/galunggong-new.webp",
    category: FishCategory.SALTWATER,
    origin: "Mindoro, Philippines",
    isHighSupply: true,
    isOnSale: true,
    isFrozen: false,
    supplyLevel: 8,
    weight: {
      min: 0.2,
      max: 0.5,
    },
  },
  {
    id: "bangus",
    nameEn: "Milkfish",
    nameFil: "Bangus",
    description: "The national fish of the Philippines, known for its tender meat and versatility in Filipino cuisine.",
    price: 160,
    oldPrice: 190,
    image: "/images/bangus-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Pangasinan, Philippines",
    isHighSupply: true,
    isOnSale: true,
    isFrozen: false,
    supplyLevel: 9,
    weight: {
      min: 0.5,
      max: 1.2,
    },
  },
  {
    id: "bangus-frozen",
    nameEn: "Milkfish",
    nameFil: "Bangus",
    description: "Frozen milkfish, perfect for Filipino classics like daing na bangus and sinigang.",
    price: 110,
    image: "/images/bangus-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Pangasinan, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 9,
    weight: {
      min: 0.5,
      max: 1.0,
    },
  },
  {
    id: "galunggong-frozen",
    nameEn: "Mackerel Scad",
    nameFil: "Galunggong",
    description: "Frozen mackerel scad, economical and convenient with the same great taste.",
    price: 80,
    image: "/images/galunggong-new.webp",
    category: FishCategory.SALTWATER,
    origin: "Mindoro, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 9,
    weight: {
      min: 0.2,
      max: 0.5,
    },
  },
  {
    id: "lapu-lapu",
    nameEn: "Grouper",
    nameFil: "Lapu-Lapu",
    description: "A premium fish with firm white flesh, perfect for steaming or grilling.",
    price: 350,
    image: "/images/lapu-lapu-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Cebu, Philippines",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 5,
    weight: {
      min: 0.8,
      max: 2.5,
    },
  },
  {
    id: "lapu-lapu-frozen",
    nameEn: "Grouper",
    nameFil: "Lapu-Lapu",
    description: "Frozen grouper fillets, premium quality at a more affordable price.",
    price: 220,
    image: "/images/lapu-lapu-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Cebu, Philippines",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 6,
    weight: {
      min: 0.8,
      max: 2.0,
    },
  },
  {
    id: "tambakol",
    nameEn: "Skipjack Tuna",
    nameFil: "Tambakol",
    description: "A smaller tuna variety with dark, flavorful meat, excellent for grilling.",
    price: 220,
    image: "/images/tambakol.jpeg",
    category: FishCategory.SALTWATER,
    origin: "General Santos, Philippines",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 6,
    weight: {
      min: 1.0,
      max: 3.0,
    },
  },
  {
    id: "tambakol-frozen",
    nameEn: "Skipjack Tuna",
    nameFil: "Tambakol",
    description: "Frozen skipjack tuna steaks, perfect for grilling and searing.",
    price: 150,
    image: "/images/tambakol.jpeg",
    category: FishCategory.SALTWATER,
    origin: "General Santos, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 8,
    weight: {
      min: 0.8,
      max: 2.0,
    },
  },
  {
    id: "salmon",
    nameEn: "Salmon",
    nameFil: "Salmon",
    description: "Imported premium fish with rich flavor and high omega-3 content.",
    price: 480,
    image: "/images/salmon-new.jpeg",
    category: FishCategory.IMPORTED,
    origin: "Norway",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 4,
    weight: {
      min: 0.5,
      max: 1.5,
    },
  },
  {
    id: "salmon-frozen",
    nameEn: "Salmon",
    nameFil: "Salmon",
    description: "Frozen salmon fillets, imported premium quality at a more accessible price.",
    price: 320,
    image: "/images/salmon-new.jpeg",
    category: FishCategory.IMPORTED,
    origin: "Norway",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 7,
    weight: {
      min: 0.2,
      max: 0.5,
    },
  },
  {
    id: "dalagang-bukid",
    nameEn: "Yellow Tail Fusilier",
    nameFil: "Dalagang Bukid",
    description: "A colorful reef fish with delicate flavor, popular in Filipino households.",
    price: 180,
    image: "/images/dorado.webp",
    category: FishCategory.SALTWATER,
    origin: "Palawan, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 7,
    weight: {
      min: 0.3,
      max: 0.7,
    },
  },
  {
    id: "maya-maya",
    nameEn: "Red Snapper",
    nameFil: "Maya-Maya",
    description: "A premium reef fish with firm texture and sweet flavor, excellent for grilling or steaming.",
    price: 280,
    image: "/images/maya-maya.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Batangas, Philippines",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 5,
    weight: {
      min: 0.7,
      max: 2.0,
    },
  },
  {
    id: "maya-maya-frozen",
    nameEn: "Red Snapper",
    nameFil: "Maya-Maya",
    description: "Frozen red snapper fillets, premium quality at a more affordable price.",
    price: 180,
    image: "/images/maya-maya.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Batangas, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 7,
    weight: {
      min: 0.5,
      max: 1.0,
    },
  },
  {
    id: "alumahan",
    nameEn: "Long-Jawed Mackerel",
    nameFil: "Alumahan",
    description: "A flavorful mackerel variety, perfect for Filipino sinigang or grilling.",
    price: 180,
    oldPrice: 220,
    image: "/images/mackerel.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Quezon, Philippines",
    isHighSupply: true,
    isOnSale: true,
    isFrozen: false,
    supplyLevel: 8,
    weight: {
      min: 0.3,
      max: 0.8,
    },
  },
  {
    id: "bisugo",
    nameEn: "Thread-Fin Bream",
    nameFil: "Bisugo",
    description: "A small but flavorful fish, perfect for frying or using in soups.",
    price: 150,
    image: "/placeholder-mosj0.png",
    category: FishCategory.SALTWATER,
    origin: "Mindoro, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 7,
    weight: {
      min: 0.2,
      max: 0.5,
    },
  },
  {
    id: "tanigue",
    nameEn: "Spanish Mackerel",
    nameFil: "Tanigue",
    description: "A premium fish with firm flesh, excellent for kinilaw (Filipino ceviche) and grilled dishes.",
    price: 320,
    image: "/images/tanigue-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Iloilo, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 7,
    weight: {
      min: 0.8,
      max: 2.5,
    },
  },
  {
    id: "tanigue-frozen",
    nameEn: "Spanish Mackerel",
    nameFil: "Tanigue",
    description: "Frozen Spanish mackerel, perfect for sashimi, kinilaw, or grilling with minimal seasoning.",
    price: 220,
    image: "/images/tanigue-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Iloilo, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 8,
    weight: {
      min: 0.6,
      max: 2.0,
    },
  },
  {
    id: "dilis",
    nameEn: "Anchovy",
    nameFil: "Dilis",
    description: "Tiny fish with big flavor, perfect for frying until crispy.",
    price: 120,
    image: "/images/sardines-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Zamboanga, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 9,
    weight: {
      min: 0.1,
      max: 0.2,
    },
  },
  {
    id: "dilis-frozen",
    nameEn: "Anchovy",
    nameFil: "Dilis",
    description: "Frozen anchovies, ready to fry for a crispy snack or side dish.",
    price: 80,
    image: "/images/sardines-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Zamboanga, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 10,
    weight: {
      min: 0.1,
      max: 0.2,
    },
  },
  {
    id: "tulingan",
    nameEn: "Mackerel Tuna",
    nameFil: "Tulingan",
    description: "A smaller tuna variety with rich flavor, excellent for everyday Filipino dishes.",
    price: 170,
    image: "/images/mackerel.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Mindanao, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 7,
    weight: {
      min: 0.4,
      max: 1.0,
    },
  },
  {
    id: "sapsap",
    nameEn: "Ponyfish",
    nameFil: "Sapsap",
    description: "A small, silvery fish with delicate flavor, perfect for frying.",
    price: 130,
    image: "/placeholder-p4niv.png",
    category: FishCategory.SALTWATER,
    origin: "Manila Bay, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 8,
    weight: {
      min: 0.2,
      max: 0.4,
    },
  },
  {
    id: "flounder",
    nameEn: "Flounder",
    nameFil: "Palad",
    description: "A flat fish with both eyes on one side, known for its delicate, mild flavor and tender texture.",
    price: 250,
    image: "/images/flounder-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Batangas, Philippines",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 6,
    weight: {
      min: 0.5,
      max: 1.2,
    },
  },
  {
    id: "flounder-frozen",
    nameEn: "Flounder",
    nameFil: "Palad",
    description:
      "Frozen flounder fillets, perfect for baking or pan-frying with minimal seasoning to enjoy its natural flavor.",
    price: 160,
    image: "/images/flounder-new.jpeg",
    category: FishCategory.SALTWATER,
    origin: "Batangas, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 7,
    weight: {
      min: 0.4,
      max: 1.0,
    },
  },
  {
    id: "dorado",
    nameEn: "Dorado",
    nameFil: "Dorado",
    description: "Also known as mahi-mahi, this fish has a sweet, mild flavor and firm texture perfect for grilling.",
    price: 280,
    image: "/images/dorado.webp",
    category: FishCategory.IMPORTED,
    origin: "Pacific Ocean",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 5,
    weight: {
      min: 0.8,
      max: 2.0,
    },
  },
  {
    id: "dorado-frozen",
    nameEn: "Dorado",
    nameFil: "Dorado",
    description: "Frozen dorado fillets, excellent for grilling, baking, or pan-searing with minimal seasoning.",
    price: 180,
    image: "/images/dorado.webp",
    category: FishCategory.IMPORTED,
    origin: "Pacific Ocean",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 6,
    weight: {
      min: 0.5,
      max: 1.5,
    },
  },
  {
    id: "talakitok",
    nameEn: "Trevally",
    nameFil: "Talakitok",
    description: "A popular game fish with firm flesh and rich flavor, excellent for grilling or in sinigang.",
    price: 220,
    image: "/placeholder.svg?key=talakitok",
    category: FishCategory.SALTWATER,
    origin: "Batangas, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 7,
    weight: {
      min: 0.5,
      max: 2.0,
    },
  },
  {
    id: "salay-salay",
    nameEn: "Mackerel Scad",
    nameFil: "Salay-Salay",
    description: "Similar to galunggong but smaller, with tender flesh perfect for frying or grilling.",
    price: 140,
    image: "/images/galunggong.webp",
    category: FishCategory.SALTWATER,
    origin: "Mindoro, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 8,
    weight: {
      min: 0.2,
      max: 0.4,
    },
  },
  {
    id: "matambaka",
    nameEn: "Big-Eye Scad",
    nameFil: "Matambaka",
    description: "A relative of the mackerel family with firm flesh, excellent for grilling or frying.",
    price: 160,
    image: "/placeholder.svg?key=matambaka",
    category: FishCategory.SALTWATER,
    origin: "Quezon, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 7,
    weight: {
      min: 0.3,
      max: 0.6,
    },
  },
  {
    id: "espada",
    nameEn: "Swordfish",
    nameFil: "Espada",
    description: "A large predatory fish with firm, meaty flesh, perfect for grilling or pan-searing.",
    price: 350,
    image: "/placeholder.svg?key=espada",
    category: FishCategory.SALTWATER,
    origin: "Batangas, Philippines",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 5,
    weight: {
      min: 1.0,
      max: 3.0,
    },
  },
  {
    id: "kitang",
    nameEn: "Rabbitfish",
    nameFil: "Kitang",
    description: "A reef fish with delicate flavor, popular for grilling or in sinigang.",
    price: 200,
    image: "/placeholder.svg?key=kitang",
    category: FishCategory.SALTWATER,
    origin: "Palawan, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 7,
    weight: {
      min: 0.3,
      max: 0.7,
    },
  },
  {
    id: "labahita",
    nameEn: "Surgeonfish",
    nameFil: "Labahita",
    description: "A reef fish with distinctive flavor, excellent for grilling or in sinigang.",
    price: 220,
    image: "/placeholder.svg?key=labahita",
    category: FishCategory.SALTWATER,
    origin: "Cebu, Philippines",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 6,
    weight: {
      min: 0.4,
      max: 0.8,
    },
  },
  {
    id: "tuna",
    nameEn: "Yellowfin Tuna",
    nameFil: "Tambakol",
    description: "Premium tuna with firm, meaty flesh, excellent for grilling, searing, or as sashimi.",
    price: 380,
    image: "/images/tambakol.jpeg",
    category: FishCategory.SALTWATER,
    origin: "General Santos, Philippines",
    isHighSupply: false,
    isOnSale: false,
    isFrozen: false,
    supplyLevel: 5,
    weight: {
      min: 1.5,
      max: 4.0,
    },
  },
  {
    id: "tuna-frozen",
    nameEn: "Yellowfin Tuna",
    nameFil: "Tambakol",
    description: "Frozen premium tuna steaks, perfect for grilling or sashimi.",
    price: 240,
    image: "/images/tambakol.jpeg",
    category: FishCategory.SALTWATER,
    origin: "General Santos, Philippines",
    isHighSupply: true,
    isOnSale: false,
    isFrozen: true,
    supplyLevel: 7,
    weight: {
      min: 0.5,
      max: 1.0,
    },
  },
]

export const popularFish = allFish.filter((fish) =>
  ["galunggong", "lapu-lapu", "tanigue", "maya-maya", "dalagang-bukid", "tuna"].includes(fish.id),
)

export const highSupplyFish = allFish.filter((fish) => fish.isHighSupply && !fish.isFrozen).slice(0, 4)

export const freshFish = allFish.filter((fish) => !fish.isFrozen)
export const frozenFish = allFish.filter((fish) => fish.isFrozen)
